Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/pi/Projects/envsensor/envsensor_livingroom.py", line 18, in <module>
    temperature, pressure, humidity = bme280.readBME280All()
  File "/home/pi/Projects/envsensor/bme280.py", line 64, in readBME280All
    bus.write_byte_data(addr, REG_CONTROL_HUM, OVERSAMPLE_HUM)
OSError: [Errno 121] Remote I/O error
